type TRAY_CHANGE_LOCATION_EVENT = 'TRAY_CHANGE_LOCATION'
type TRAY_SWITCH_PROXY_EVENT = 'TRAY_SWITCH_PROXY'
type TRAY_SWITCH_AUTO_START_EVENT = 'TRAY_SWITCH_AUTO_START'

type TRAY_EVENT =
  | TRAY_CHANGE_LOCATION_EVENT
  | TRAY_SWITCH_PROXY_EVENT
  | TRAY_SWITCH_AUTO_START_EVENT
